---
platform: linux

image_resource:
  type: docker-image
  source: { repository: busybox }

inputs:
  - name: parmesan-lambdas
  
run:
  path: parmesan-lambdas/src/main/back/deploy/scripts/zip-parmesan.sh
